// Code generated by protoc-gen-go. DO NOT EDIT.
// source: standard.proto

package standard

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 状态
type State int32

const (
	State_UNKNOWN              State = 0
	State_SUCCESS              State = 1
	State_FAILURE              State = 2
	State_SERVICE_ERROR        State = 3
	State_PARAMS_INVALID       State = 4
	State_ILLEGAL_REQUEST      State = 5
	State_UNIT_DATA_EXPIRED    State = 6
	State_UNIT_DATA_NOT_EXIST  State = 7
	State_UNIT_DATA_NOT_ACTIVE State = 8
	State_DB_OPERATION_FATLURE State = 9
)

var State_name = map[int32]string{
	0: "UNKNOWN",
	1: "SUCCESS",
	2: "FAILURE",
	3: "SERVICE_ERROR",
	4: "PARAMS_INVALID",
	5: "ILLEGAL_REQUEST",
	6: "UNIT_DATA_EXPIRED",
	7: "UNIT_DATA_NOT_EXIST",
	8: "UNIT_DATA_NOT_ACTIVE",
	9: "DB_OPERATION_FATLURE",
}

var State_value = map[string]int32{
	"UNKNOWN":              0,
	"SUCCESS":              1,
	"FAILURE":              2,
	"SERVICE_ERROR":        3,
	"PARAMS_INVALID":       4,
	"ILLEGAL_REQUEST":      5,
	"UNIT_DATA_EXPIRED":    6,
	"UNIT_DATA_NOT_EXIST":  7,
	"UNIT_DATA_NOT_ACTIVE": 8,
	"DB_OPERATION_FATLURE": 9,
}

func (x State) String() string {
	return proto.EnumName(State_name, int32(x))
}

func (State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{0}
}

// 单位数据
type UnitData struct {
	Body                 string   `protobuf:"bytes,1,opt,name=Body,proto3" json:"Body,omitempty"`
	ExpiryTime           string   `protobuf:"bytes,3,opt,name=ExpiryTime,proto3" json:"ExpiryTime,omitempty"`
	CreatedTime          string   `protobuf:"bytes,4,opt,name=CreatedTime,proto3" json:"CreatedTime,omitempty"`
	DestroyTime          string   `protobuf:"bytes,5,opt,name=DestroyTime,proto3" json:"DestroyTime,omitempty"`
	EffectiveTime        string   `protobuf:"bytes,6,opt,name=EffectiveTime,proto3" json:"EffectiveTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnitData) Reset()         { *m = UnitData{} }
func (m *UnitData) String() string { return proto.CompactTextString(m) }
func (*UnitData) ProtoMessage()    {}
func (*UnitData) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{0}
}

func (m *UnitData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnitData.Unmarshal(m, b)
}
func (m *UnitData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnitData.Marshal(b, m, deterministic)
}
func (m *UnitData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnitData.Merge(m, src)
}
func (m *UnitData) XXX_Size() int {
	return xxx_messageInfo_UnitData.Size(m)
}
func (m *UnitData) XXX_DiscardUnknown() {
	xxx_messageInfo_UnitData.DiscardUnknown(m)
}

var xxx_messageInfo_UnitData proto.InternalMessageInfo

func (m *UnitData) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *UnitData) GetExpiryTime() string {
	if m != nil {
		return m.ExpiryTime
	}
	return ""
}

func (m *UnitData) GetCreatedTime() string {
	if m != nil {
		return m.CreatedTime
	}
	return ""
}

func (m *UnitData) GetDestroyTime() string {
	if m != nil {
		return m.DestroyTime
	}
	return ""
}

func (m *UnitData) GetEffectiveTime() string {
	if m != nil {
		return m.EffectiveTime
	}
	return ""
}

type CreateUnitDataRequest struct {
	Body                 string   `protobuf:"bytes,1,opt,name=Body,proto3" json:"Body,omitempty"`
	ExpiryTime           string   `protobuf:"bytes,2,opt,name=ExpiryTime,proto3" json:"ExpiryTime,omitempty"`
	DestroyTime          string   `protobuf:"bytes,3,opt,name=DestroyTime,proto3" json:"DestroyTime,omitempty"`
	EffectiveTime        string   `protobuf:"bytes,4,opt,name=EffectiveTime,proto3" json:"EffectiveTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUnitDataRequest) Reset()         { *m = CreateUnitDataRequest{} }
func (m *CreateUnitDataRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUnitDataRequest) ProtoMessage()    {}
func (*CreateUnitDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{1}
}

func (m *CreateUnitDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUnitDataRequest.Unmarshal(m, b)
}
func (m *CreateUnitDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUnitDataRequest.Marshal(b, m, deterministic)
}
func (m *CreateUnitDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUnitDataRequest.Merge(m, src)
}
func (m *CreateUnitDataRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUnitDataRequest.Size(m)
}
func (m *CreateUnitDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUnitDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUnitDataRequest proto.InternalMessageInfo

func (m *CreateUnitDataRequest) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *CreateUnitDataRequest) GetExpiryTime() string {
	if m != nil {
		return m.ExpiryTime
	}
	return ""
}

func (m *CreateUnitDataRequest) GetDestroyTime() string {
	if m != nil {
		return m.DestroyTime
	}
	return ""
}

func (m *CreateUnitDataRequest) GetEffectiveTime() string {
	if m != nil {
		return m.EffectiveTime
	}
	return ""
}

type CreateUnitDataResponse struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	State                State    `protobuf:"varint,2,opt,name=State,proto3,enum=standard.State" json:"State,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUnitDataResponse) Reset()         { *m = CreateUnitDataResponse{} }
func (m *CreateUnitDataResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUnitDataResponse) ProtoMessage()    {}
func (*CreateUnitDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{2}
}

func (m *CreateUnitDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUnitDataResponse.Unmarshal(m, b)
}
func (m *CreateUnitDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUnitDataResponse.Marshal(b, m, deterministic)
}
func (m *CreateUnitDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUnitDataResponse.Merge(m, src)
}
func (m *CreateUnitDataResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUnitDataResponse.Size(m)
}
func (m *CreateUnitDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUnitDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUnitDataResponse proto.InternalMessageInfo

func (m *CreateUnitDataResponse) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *CreateUnitDataResponse) GetState() State {
	if m != nil {
		return m.State
	}
	return State_UNKNOWN
}

func (m *CreateUnitDataResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetUnitDataByKeyRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUnitDataByKeyRequest) Reset()         { *m = GetUnitDataByKeyRequest{} }
func (m *GetUnitDataByKeyRequest) String() string { return proto.CompactTextString(m) }
func (*GetUnitDataByKeyRequest) ProtoMessage()    {}
func (*GetUnitDataByKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{3}
}

func (m *GetUnitDataByKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUnitDataByKeyRequest.Unmarshal(m, b)
}
func (m *GetUnitDataByKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUnitDataByKeyRequest.Marshal(b, m, deterministic)
}
func (m *GetUnitDataByKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUnitDataByKeyRequest.Merge(m, src)
}
func (m *GetUnitDataByKeyRequest) XXX_Size() int {
	return xxx_messageInfo_GetUnitDataByKeyRequest.Size(m)
}
func (m *GetUnitDataByKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUnitDataByKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUnitDataByKeyRequest proto.InternalMessageInfo

func (m *GetUnitDataByKeyRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetUnitDataByKeyResponse struct {
	State                State     `protobuf:"varint,1,opt,name=State,proto3,enum=standard.State" json:"State,omitempty"`
	Message              string    `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	Data                 *UnitData `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetUnitDataByKeyResponse) Reset()         { *m = GetUnitDataByKeyResponse{} }
func (m *GetUnitDataByKeyResponse) String() string { return proto.CompactTextString(m) }
func (*GetUnitDataByKeyResponse) ProtoMessage()    {}
func (*GetUnitDataByKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{4}
}

func (m *GetUnitDataByKeyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUnitDataByKeyResponse.Unmarshal(m, b)
}
func (m *GetUnitDataByKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUnitDataByKeyResponse.Marshal(b, m, deterministic)
}
func (m *GetUnitDataByKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUnitDataByKeyResponse.Merge(m, src)
}
func (m *GetUnitDataByKeyResponse) XXX_Size() int {
	return xxx_messageInfo_GetUnitDataByKeyResponse.Size(m)
}
func (m *GetUnitDataByKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUnitDataByKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUnitDataByKeyResponse proto.InternalMessageInfo

func (m *GetUnitDataByKeyResponse) GetState() State {
	if m != nil {
		return m.State
	}
	return State_UNKNOWN
}

func (m *GetUnitDataByKeyResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetUnitDataByKeyResponse) GetData() *UnitData {
	if m != nil {
		return m.Data
	}
	return nil
}

type DestroyUnitDataByKeyRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DestroyUnitDataByKeyRequest) Reset()         { *m = DestroyUnitDataByKeyRequest{} }
func (m *DestroyUnitDataByKeyRequest) String() string { return proto.CompactTextString(m) }
func (*DestroyUnitDataByKeyRequest) ProtoMessage()    {}
func (*DestroyUnitDataByKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{5}
}

func (m *DestroyUnitDataByKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DestroyUnitDataByKeyRequest.Unmarshal(m, b)
}
func (m *DestroyUnitDataByKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DestroyUnitDataByKeyRequest.Marshal(b, m, deterministic)
}
func (m *DestroyUnitDataByKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DestroyUnitDataByKeyRequest.Merge(m, src)
}
func (m *DestroyUnitDataByKeyRequest) XXX_Size() int {
	return xxx_messageInfo_DestroyUnitDataByKeyRequest.Size(m)
}
func (m *DestroyUnitDataByKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DestroyUnitDataByKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DestroyUnitDataByKeyRequest proto.InternalMessageInfo

func (m *DestroyUnitDataByKeyRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type DestroyUnitDataByKeyResponse struct {
	State                State    `protobuf:"varint,1,opt,name=State,proto3,enum=standard.State" json:"State,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DestroyUnitDataByKeyResponse) Reset()         { *m = DestroyUnitDataByKeyResponse{} }
func (m *DestroyUnitDataByKeyResponse) String() string { return proto.CompactTextString(m) }
func (*DestroyUnitDataByKeyResponse) ProtoMessage()    {}
func (*DestroyUnitDataByKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{6}
}

func (m *DestroyUnitDataByKeyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DestroyUnitDataByKeyResponse.Unmarshal(m, b)
}
func (m *DestroyUnitDataByKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DestroyUnitDataByKeyResponse.Marshal(b, m, deterministic)
}
func (m *DestroyUnitDataByKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DestroyUnitDataByKeyResponse.Merge(m, src)
}
func (m *DestroyUnitDataByKeyResponse) XXX_Size() int {
	return xxx_messageInfo_DestroyUnitDataByKeyResponse.Size(m)
}
func (m *DestroyUnitDataByKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DestroyUnitDataByKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DestroyUnitDataByKeyResponse proto.InternalMessageInfo

func (m *DestroyUnitDataByKeyResponse) GetState() State {
	if m != nil {
		return m.State
	}
	return State_UNKNOWN
}

func (m *DestroyUnitDataByKeyResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type UpdateUnitDataBodyByKeyRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Body                 string   `protobuf:"bytes,2,opt,name=Body,proto3" json:"Body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUnitDataBodyByKeyRequest) Reset()         { *m = UpdateUnitDataBodyByKeyRequest{} }
func (m *UpdateUnitDataBodyByKeyRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUnitDataBodyByKeyRequest) ProtoMessage()    {}
func (*UpdateUnitDataBodyByKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{7}
}

func (m *UpdateUnitDataBodyByKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUnitDataBodyByKeyRequest.Unmarshal(m, b)
}
func (m *UpdateUnitDataBodyByKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUnitDataBodyByKeyRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUnitDataBodyByKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUnitDataBodyByKeyRequest.Merge(m, src)
}
func (m *UpdateUnitDataBodyByKeyRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUnitDataBodyByKeyRequest.Size(m)
}
func (m *UpdateUnitDataBodyByKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUnitDataBodyByKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUnitDataBodyByKeyRequest proto.InternalMessageInfo

func (m *UpdateUnitDataBodyByKeyRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *UpdateUnitDataBodyByKeyRequest) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type UpdateUnitDataBodyByKeyResponse struct {
	State                State    `protobuf:"varint,1,opt,name=State,proto3,enum=standard.State" json:"State,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUnitDataBodyByKeyResponse) Reset()         { *m = UpdateUnitDataBodyByKeyResponse{} }
func (m *UpdateUnitDataBodyByKeyResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUnitDataBodyByKeyResponse) ProtoMessage()    {}
func (*UpdateUnitDataBodyByKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{8}
}

func (m *UpdateUnitDataBodyByKeyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUnitDataBodyByKeyResponse.Unmarshal(m, b)
}
func (m *UpdateUnitDataBodyByKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUnitDataBodyByKeyResponse.Marshal(b, m, deterministic)
}
func (m *UpdateUnitDataBodyByKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUnitDataBodyByKeyResponse.Merge(m, src)
}
func (m *UpdateUnitDataBodyByKeyResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUnitDataBodyByKeyResponse.Size(m)
}
func (m *UpdateUnitDataBodyByKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUnitDataBodyByKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUnitDataBodyByKeyResponse proto.InternalMessageInfo

func (m *UpdateUnitDataBodyByKeyResponse) GetState() State {
	if m != nil {
		return m.State
	}
	return State_UNKNOWN
}

func (m *UpdateUnitDataBodyByKeyResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type UpdateUnitDataExpiryTimeByKeyRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	ExpiryTime           string   `protobuf:"bytes,2,opt,name=ExpiryTime,proto3" json:"ExpiryTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUnitDataExpiryTimeByKeyRequest) Reset()         { *m = UpdateUnitDataExpiryTimeByKeyRequest{} }
func (m *UpdateUnitDataExpiryTimeByKeyRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUnitDataExpiryTimeByKeyRequest) ProtoMessage()    {}
func (*UpdateUnitDataExpiryTimeByKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{9}
}

func (m *UpdateUnitDataExpiryTimeByKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUnitDataExpiryTimeByKeyRequest.Unmarshal(m, b)
}
func (m *UpdateUnitDataExpiryTimeByKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUnitDataExpiryTimeByKeyRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUnitDataExpiryTimeByKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUnitDataExpiryTimeByKeyRequest.Merge(m, src)
}
func (m *UpdateUnitDataExpiryTimeByKeyRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUnitDataExpiryTimeByKeyRequest.Size(m)
}
func (m *UpdateUnitDataExpiryTimeByKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUnitDataExpiryTimeByKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUnitDataExpiryTimeByKeyRequest proto.InternalMessageInfo

func (m *UpdateUnitDataExpiryTimeByKeyRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *UpdateUnitDataExpiryTimeByKeyRequest) GetExpiryTime() string {
	if m != nil {
		return m.ExpiryTime
	}
	return ""
}

type UpdateUnitDataExpiryTimeByKeyResponse struct {
	State                State    `protobuf:"varint,1,opt,name=State,proto3,enum=standard.State" json:"State,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUnitDataExpiryTimeByKeyResponse) Reset()         { *m = UpdateUnitDataExpiryTimeByKeyResponse{} }
func (m *UpdateUnitDataExpiryTimeByKeyResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUnitDataExpiryTimeByKeyResponse) ProtoMessage()    {}
func (*UpdateUnitDataExpiryTimeByKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{10}
}

func (m *UpdateUnitDataExpiryTimeByKeyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUnitDataExpiryTimeByKeyResponse.Unmarshal(m, b)
}
func (m *UpdateUnitDataExpiryTimeByKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUnitDataExpiryTimeByKeyResponse.Marshal(b, m, deterministic)
}
func (m *UpdateUnitDataExpiryTimeByKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUnitDataExpiryTimeByKeyResponse.Merge(m, src)
}
func (m *UpdateUnitDataExpiryTimeByKeyResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUnitDataExpiryTimeByKeyResponse.Size(m)
}
func (m *UpdateUnitDataExpiryTimeByKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUnitDataExpiryTimeByKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUnitDataExpiryTimeByKeyResponse proto.InternalMessageInfo

func (m *UpdateUnitDataExpiryTimeByKeyResponse) GetState() State {
	if m != nil {
		return m.State
	}
	return State_UNKNOWN
}

func (m *UpdateUnitDataExpiryTimeByKeyResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type UpdateUnitDataDestroyTimeByKeyRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	DestroyTime          string   `protobuf:"bytes,2,opt,name=DestroyTime,proto3" json:"DestroyTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUnitDataDestroyTimeByKeyRequest) Reset()         { *m = UpdateUnitDataDestroyTimeByKeyRequest{} }
func (m *UpdateUnitDataDestroyTimeByKeyRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUnitDataDestroyTimeByKeyRequest) ProtoMessage()    {}
func (*UpdateUnitDataDestroyTimeByKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{11}
}

func (m *UpdateUnitDataDestroyTimeByKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUnitDataDestroyTimeByKeyRequest.Unmarshal(m, b)
}
func (m *UpdateUnitDataDestroyTimeByKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUnitDataDestroyTimeByKeyRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUnitDataDestroyTimeByKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUnitDataDestroyTimeByKeyRequest.Merge(m, src)
}
func (m *UpdateUnitDataDestroyTimeByKeyRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUnitDataDestroyTimeByKeyRequest.Size(m)
}
func (m *UpdateUnitDataDestroyTimeByKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUnitDataDestroyTimeByKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUnitDataDestroyTimeByKeyRequest proto.InternalMessageInfo

func (m *UpdateUnitDataDestroyTimeByKeyRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *UpdateUnitDataDestroyTimeByKeyRequest) GetDestroyTime() string {
	if m != nil {
		return m.DestroyTime
	}
	return ""
}

type UpdateUnitDataDestroyTimeByKeyResponse struct {
	State                State    `protobuf:"varint,1,opt,name=State,proto3,enum=standard.State" json:"State,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUnitDataDestroyTimeByKeyResponse) Reset() {
	*m = UpdateUnitDataDestroyTimeByKeyResponse{}
}
func (m *UpdateUnitDataDestroyTimeByKeyResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUnitDataDestroyTimeByKeyResponse) ProtoMessage()    {}
func (*UpdateUnitDataDestroyTimeByKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{12}
}

func (m *UpdateUnitDataDestroyTimeByKeyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUnitDataDestroyTimeByKeyResponse.Unmarshal(m, b)
}
func (m *UpdateUnitDataDestroyTimeByKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUnitDataDestroyTimeByKeyResponse.Marshal(b, m, deterministic)
}
func (m *UpdateUnitDataDestroyTimeByKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUnitDataDestroyTimeByKeyResponse.Merge(m, src)
}
func (m *UpdateUnitDataDestroyTimeByKeyResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUnitDataDestroyTimeByKeyResponse.Size(m)
}
func (m *UpdateUnitDataDestroyTimeByKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUnitDataDestroyTimeByKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUnitDataDestroyTimeByKeyResponse proto.InternalMessageInfo

func (m *UpdateUnitDataDestroyTimeByKeyResponse) GetState() State {
	if m != nil {
		return m.State
	}
	return State_UNKNOWN
}

func (m *UpdateUnitDataDestroyTimeByKeyResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type UpdateUnitDataEffectiveTimeByKeyRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	EffectiveTime        string   `protobuf:"bytes,2,opt,name=EffectiveTime,proto3" json:"EffectiveTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUnitDataEffectiveTimeByKeyRequest) Reset() {
	*m = UpdateUnitDataEffectiveTimeByKeyRequest{}
}
func (m *UpdateUnitDataEffectiveTimeByKeyRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUnitDataEffectiveTimeByKeyRequest) ProtoMessage()    {}
func (*UpdateUnitDataEffectiveTimeByKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{13}
}

func (m *UpdateUnitDataEffectiveTimeByKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUnitDataEffectiveTimeByKeyRequest.Unmarshal(m, b)
}
func (m *UpdateUnitDataEffectiveTimeByKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUnitDataEffectiveTimeByKeyRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUnitDataEffectiveTimeByKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUnitDataEffectiveTimeByKeyRequest.Merge(m, src)
}
func (m *UpdateUnitDataEffectiveTimeByKeyRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUnitDataEffectiveTimeByKeyRequest.Size(m)
}
func (m *UpdateUnitDataEffectiveTimeByKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUnitDataEffectiveTimeByKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUnitDataEffectiveTimeByKeyRequest proto.InternalMessageInfo

func (m *UpdateUnitDataEffectiveTimeByKeyRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *UpdateUnitDataEffectiveTimeByKeyRequest) GetEffectiveTime() string {
	if m != nil {
		return m.EffectiveTime
	}
	return ""
}

type UpdateUnitDataEffectiveTimeByKeyResponse struct {
	State                State    `protobuf:"varint,1,opt,name=State,proto3,enum=standard.State" json:"State,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUnitDataEffectiveTimeByKeyResponse) Reset() {
	*m = UpdateUnitDataEffectiveTimeByKeyResponse{}
}
func (m *UpdateUnitDataEffectiveTimeByKeyResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUnitDataEffectiveTimeByKeyResponse) ProtoMessage()    {}
func (*UpdateUnitDataEffectiveTimeByKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b3e239150a6a10f, []int{14}
}

func (m *UpdateUnitDataEffectiveTimeByKeyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUnitDataEffectiveTimeByKeyResponse.Unmarshal(m, b)
}
func (m *UpdateUnitDataEffectiveTimeByKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUnitDataEffectiveTimeByKeyResponse.Marshal(b, m, deterministic)
}
func (m *UpdateUnitDataEffectiveTimeByKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUnitDataEffectiveTimeByKeyResponse.Merge(m, src)
}
func (m *UpdateUnitDataEffectiveTimeByKeyResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUnitDataEffectiveTimeByKeyResponse.Size(m)
}
func (m *UpdateUnitDataEffectiveTimeByKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUnitDataEffectiveTimeByKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUnitDataEffectiveTimeByKeyResponse proto.InternalMessageInfo

func (m *UpdateUnitDataEffectiveTimeByKeyResponse) GetState() State {
	if m != nil {
		return m.State
	}
	return State_UNKNOWN
}

func (m *UpdateUnitDataEffectiveTimeByKeyResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterEnum("standard.State", State_name, State_value)
	proto.RegisterType((*UnitData)(nil), "standard.UnitData")
	proto.RegisterType((*CreateUnitDataRequest)(nil), "standard.CreateUnitDataRequest")
	proto.RegisterType((*CreateUnitDataResponse)(nil), "standard.CreateUnitDataResponse")
	proto.RegisterType((*GetUnitDataByKeyRequest)(nil), "standard.GetUnitDataByKeyRequest")
	proto.RegisterType((*GetUnitDataByKeyResponse)(nil), "standard.GetUnitDataByKeyResponse")
	proto.RegisterType((*DestroyUnitDataByKeyRequest)(nil), "standard.DestroyUnitDataByKeyRequest")
	proto.RegisterType((*DestroyUnitDataByKeyResponse)(nil), "standard.DestroyUnitDataByKeyResponse")
	proto.RegisterType((*UpdateUnitDataBodyByKeyRequest)(nil), "standard.UpdateUnitDataBodyByKeyRequest")
	proto.RegisterType((*UpdateUnitDataBodyByKeyResponse)(nil), "standard.UpdateUnitDataBodyByKeyResponse")
	proto.RegisterType((*UpdateUnitDataExpiryTimeByKeyRequest)(nil), "standard.UpdateUnitDataExpiryTimeByKeyRequest")
	proto.RegisterType((*UpdateUnitDataExpiryTimeByKeyResponse)(nil), "standard.UpdateUnitDataExpiryTimeByKeyResponse")
	proto.RegisterType((*UpdateUnitDataDestroyTimeByKeyRequest)(nil), "standard.UpdateUnitDataDestroyTimeByKeyRequest")
	proto.RegisterType((*UpdateUnitDataDestroyTimeByKeyResponse)(nil), "standard.UpdateUnitDataDestroyTimeByKeyResponse")
	proto.RegisterType((*UpdateUnitDataEffectiveTimeByKeyRequest)(nil), "standard.UpdateUnitDataEffectiveTimeByKeyRequest")
	proto.RegisterType((*UpdateUnitDataEffectiveTimeByKeyResponse)(nil), "standard.UpdateUnitDataEffectiveTimeByKeyResponse")
}

func init() { proto.RegisterFile("standard.proto", fileDescriptor_0b3e239150a6a10f) }

var fileDescriptor_0b3e239150a6a10f = []byte{
	// 700 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x96, 0xdd, 0x4e, 0xdb, 0x4c,
	0x10, 0x86, 0x71, 0x12, 0x02, 0x0c, 0x22, 0x98, 0x01, 0x3e, 0x22, 0x7f, 0x2d, 0xa4, 0x16, 0x50,
	0xda, 0x4a, 0xd0, 0xa6, 0x57, 0x60, 0x92, 0x05, 0x59, 0x04, 0x87, 0xae, 0x6d, 0x8a, 0xc4, 0x81,
	0x65, 0x9a, 0x85, 0x46, 0x55, 0x49, 0x1a, 0xbb, 0x3f, 0x39, 0x6d, 0xd5, 0xa3, 0x1e, 0xf6, 0x26,
	0x7a, 0xdc, 0x0b, 0xe9, 0x35, 0x55, 0xb6, 0xe3, 0x9f, 0x38, 0x76, 0xec, 0x4a, 0x39, 0xcb, 0xee,
	0xbe, 0x33, 0xf3, 0xcc, 0x78, 0xf7, 0x05, 0xa8, 0x58, 0xb6, 0x79, 0xdf, 0x31, 0x07, 0x9d, 0xc3,
	0xfe, 0xa0, 0x67, 0xf7, 0x70, 0xd1, 0x5f, 0x8b, 0xbf, 0x38, 0x58, 0xd4, 0xef, 0xbb, 0x76, 0xd3,
	0xb4, 0x4d, 0x44, 0x28, 0x1d, 0xf7, 0x3a, 0xc3, 0x2a, 0x57, 0xe3, 0x0e, 0x96, 0xa8, 0xfb, 0x1b,
	0xb7, 0x01, 0xc8, 0x97, 0x7e, 0x77, 0x30, 0xd4, 0xba, 0xef, 0x59, 0xb5, 0xe8, 0x9e, 0x44, 0x76,
	0xb0, 0x06, 0xcb, 0x8d, 0x01, 0x33, 0x6d, 0xd6, 0x71, 0x05, 0x25, 0x57, 0x10, 0xdd, 0x72, 0x14,
	0x4d, 0x66, 0xd9, 0x83, 0x9e, 0x97, 0x62, 0xde, 0x53, 0x44, 0xb6, 0x70, 0x17, 0x56, 0xc8, 0xed,
	0x2d, 0x7b, 0x63, 0x77, 0x3f, 0x31, 0x57, 0x53, 0x76, 0x35, 0xe3, 0x9b, 0xe2, 0x4f, 0x0e, 0x36,
	0xbd, 0xbc, 0x3e, 0x30, 0x65, 0x1f, 0x3e, 0x32, 0xcb, 0xce, 0xc1, 0x5d, 0x48, 0xe2, 0x8e, 0x52,
	0x15, 0x73, 0x50, 0x95, 0x92, 0xa8, 0xde, 0xc1, 0x7f, 0x71, 0x28, 0xab, 0xdf, 0xbb, 0xb7, 0x18,
	0xf2, 0x50, 0x3c, 0x63, 0x3e, 0x94, 0xf3, 0x13, 0xf7, 0x60, 0x5e, 0xb5, 0x4d, 0xdb, 0xc3, 0xa9,
	0xd4, 0x57, 0x0f, 0x83, 0xcf, 0xe2, 0x6e, 0x53, 0xef, 0x14, 0xab, 0xb0, 0x70, 0xce, 0x2c, 0xcb,
	0xbc, 0xf3, 0xb1, 0xfc, 0xa5, 0xf8, 0x0c, 0xb6, 0x4e, 0x99, 0xed, 0x57, 0x3a, 0x1e, 0x9e, 0xb1,
	0xa1, 0x3f, 0x83, 0x89, 0x6a, 0xe2, 0x37, 0x0e, 0xaa, 0x93, 0xea, 0x11, 0x5c, 0x80, 0xc2, 0xe5,
	0x45, 0x29, 0x8c, 0xa1, 0xe0, 0x3e, 0x94, 0x9c, 0xac, 0x2e, 0xe1, 0x72, 0x1d, 0xc3, 0xf8, 0x60,
	0x0e, 0xee, 0xb9, 0x78, 0x04, 0xff, 0x8f, 0x86, 0x9a, 0x13, 0xdb, 0x80, 0x07, 0xc9, 0x01, 0x33,
	0x22, 0x17, 0x4f, 0x60, 0x5b, 0xef, 0x77, 0x22, 0x5f, 0xcc, 0xb9, 0x2f, 0xd3, 0xa1, 0x82, 0x1b,
	0x56, 0x08, 0x6f, 0x98, 0x78, 0x03, 0x3b, 0xa9, 0x79, 0x66, 0xc5, 0x7a, 0x05, 0xbb, 0xe3, 0x35,
	0xc2, 0x1b, 0x9c, 0x41, 0x9c, 0x71, 0xff, 0xc5, 0xb7, 0xb0, 0x97, 0x91, 0x79, 0x56, 0x3d, 0x5c,
	0xc7, 0x2b, 0x45, 0x1e, 0x59, 0x46, 0x13, 0xb1, 0x47, 0x5a, 0x98, 0x78, 0xa4, 0x62, 0x17, 0xf6,
	0xb3, 0x92, 0xcf, 0xaa, 0x0f, 0x13, 0x1e, 0xc7, 0x26, 0x16, 0x35, 0x82, 0x8c, 0x4e, 0x26, 0xcc,
	0xa4, 0x90, 0x6c, 0x26, 0x07, 0xd9, 0x25, 0x66, 0xd4, 0xcf, 0xd3, 0x3f, 0xdc, 0x28, 0x03, 0x2e,
	0xc3, 0x82, 0xae, 0x9c, 0x29, 0xed, 0xd7, 0x0a, 0x3f, 0xe7, 0x2c, 0x54, 0xbd, 0xd1, 0x20, 0xaa,
	0xca, 0x73, 0xce, 0xe2, 0x44, 0x92, 0x5b, 0x3a, 0x25, 0x7c, 0x01, 0xd7, 0x60, 0x45, 0x25, 0xf4,
	0x52, 0x6e, 0x10, 0x83, 0x50, 0xda, 0xa6, 0x7c, 0x11, 0x11, 0x2a, 0x17, 0x12, 0x95, 0xce, 0x55,
	0x43, 0x56, 0x2e, 0xa5, 0x96, 0xdc, 0xe4, 0x4b, 0xb8, 0x0e, 0xab, 0x72, 0xab, 0x45, 0x4e, 0xa5,
	0x96, 0x41, 0xc9, 0x2b, 0x9d, 0xa8, 0x1a, 0x3f, 0x8f, 0x9b, 0xb0, 0xa6, 0x2b, 0xb2, 0x66, 0x34,
	0x25, 0x4d, 0x32, 0xc8, 0xd5, 0x85, 0x4c, 0x49, 0x93, 0x2f, 0xe3, 0x16, 0xac, 0x87, 0xdb, 0x4a,
	0x5b, 0x33, 0xc8, 0x95, 0xac, 0x6a, 0xfc, 0x02, 0x56, 0x61, 0x63, 0xfc, 0x40, 0x6a, 0x68, 0xf2,
	0x25, 0xe1, 0x17, 0x9d, 0x93, 0xe6, 0xb1, 0xd1, 0xbe, 0x20, 0x54, 0xd2, 0xe4, 0xb6, 0x62, 0x9c,
	0x48, 0x9a, 0xcb, 0xb7, 0x54, 0xff, 0x5d, 0x86, 0xb2, 0xfa, 0xd9, 0xec, 0xb3, 0x01, 0xea, 0x50,
	0x19, 0x77, 0x65, 0xdc, 0x09, 0xe7, 0x93, 0xf8, 0x47, 0x44, 0xa8, 0xa5, 0x0b, 0xbc, 0x89, 0x8b,
	0x73, 0x78, 0x0d, 0x7c, 0xdc, 0x51, 0xf1, 0x51, 0x18, 0x97, 0xe2, 0xcd, 0x82, 0x38, 0x4d, 0x12,
	0x24, 0xbf, 0x83, 0x8d, 0x24, 0xe3, 0xc3, 0xbd, 0x30, 0x7a, 0x8a, 0x93, 0x0a, 0xfb, 0x59, 0xb2,
	0xa0, 0x50, 0x1f, 0xb6, 0x52, 0x8c, 0x0b, 0x0f, 0x22, 0x3e, 0x3e, 0xd5, 0x23, 0x85, 0x27, 0x39,
	0x94, 0x41, 0xc5, 0xaf, 0x1c, 0x3c, 0x9c, 0xea, 0x36, 0x78, 0x98, 0x96, 0x2e, 0xd9, 0xf0, 0x84,
	0xa3, 0xdc, 0xfa, 0x00, 0xe2, 0x3b, 0x17, 0x37, 0xfe, 0xb8, 0x57, 0x60, 0x6a, 0xd6, 0x14, 0xcb,
	0x12, 0x9e, 0xe7, 0x0f, 0x08, 0x38, 0x7e, 0x70, 0x50, 0xcb, 0x7a, 0xe5, 0xf8, 0x22, 0xb5, 0xbf,
	0x34, 0xd3, 0x11, 0xea, 0xff, 0x12, 0xe2, 0xd3, 0xdc, 0x94, 0xdd, 0xff, 0x08, 0x5f, 0xfe, 0x0d,
	0x00, 0x00, 0xff, 0xff, 0xcd, 0xd3, 0xe1, 0xff, 0x23, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SwaperClient is the client API for Swaper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SwaperClient interface {
	CreateUnitData(ctx context.Context, in *CreateUnitDataRequest, opts ...grpc.CallOption) (*CreateUnitDataResponse, error)
	GetUnitDataByKey(ctx context.Context, in *GetUnitDataByKeyRequest, opts ...grpc.CallOption) (*GetUnitDataByKeyResponse, error)
	DestroyUnitDataByKey(ctx context.Context, in *DestroyUnitDataByKeyRequest, opts ...grpc.CallOption) (*DestroyUnitDataByKeyResponse, error)
	UpdateUnitDataBodyByKey(ctx context.Context, in *UpdateUnitDataBodyByKeyRequest, opts ...grpc.CallOption) (*UpdateUnitDataBodyByKeyResponse, error)
	UpdateUnitDataExpiryTimeByKey(ctx context.Context, in *UpdateUnitDataExpiryTimeByKeyRequest, opts ...grpc.CallOption) (*UpdateUnitDataExpiryTimeByKeyResponse, error)
	UpdateUnitDataDestroyTimeByKey(ctx context.Context, in *UpdateUnitDataDestroyTimeByKeyRequest, opts ...grpc.CallOption) (*UpdateUnitDataDestroyTimeByKeyResponse, error)
	UpdateUnitDataEffectiveTimeByKey(ctx context.Context, in *UpdateUnitDataEffectiveTimeByKeyRequest, opts ...grpc.CallOption) (*UpdateUnitDataEffectiveTimeByKeyResponse, error)
}

type swaperClient struct {
	cc *grpc.ClientConn
}

func NewSwaperClient(cc *grpc.ClientConn) SwaperClient {
	return &swaperClient{cc}
}

func (c *swaperClient) CreateUnitData(ctx context.Context, in *CreateUnitDataRequest, opts ...grpc.CallOption) (*CreateUnitDataResponse, error) {
	out := new(CreateUnitDataResponse)
	err := c.cc.Invoke(ctx, "/standard.Swaper/CreateUnitData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swaperClient) GetUnitDataByKey(ctx context.Context, in *GetUnitDataByKeyRequest, opts ...grpc.CallOption) (*GetUnitDataByKeyResponse, error) {
	out := new(GetUnitDataByKeyResponse)
	err := c.cc.Invoke(ctx, "/standard.Swaper/GetUnitDataByKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swaperClient) DestroyUnitDataByKey(ctx context.Context, in *DestroyUnitDataByKeyRequest, opts ...grpc.CallOption) (*DestroyUnitDataByKeyResponse, error) {
	out := new(DestroyUnitDataByKeyResponse)
	err := c.cc.Invoke(ctx, "/standard.Swaper/DestroyUnitDataByKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swaperClient) UpdateUnitDataBodyByKey(ctx context.Context, in *UpdateUnitDataBodyByKeyRequest, opts ...grpc.CallOption) (*UpdateUnitDataBodyByKeyResponse, error) {
	out := new(UpdateUnitDataBodyByKeyResponse)
	err := c.cc.Invoke(ctx, "/standard.Swaper/UpdateUnitDataBodyByKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swaperClient) UpdateUnitDataExpiryTimeByKey(ctx context.Context, in *UpdateUnitDataExpiryTimeByKeyRequest, opts ...grpc.CallOption) (*UpdateUnitDataExpiryTimeByKeyResponse, error) {
	out := new(UpdateUnitDataExpiryTimeByKeyResponse)
	err := c.cc.Invoke(ctx, "/standard.Swaper/UpdateUnitDataExpiryTimeByKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swaperClient) UpdateUnitDataDestroyTimeByKey(ctx context.Context, in *UpdateUnitDataDestroyTimeByKeyRequest, opts ...grpc.CallOption) (*UpdateUnitDataDestroyTimeByKeyResponse, error) {
	out := new(UpdateUnitDataDestroyTimeByKeyResponse)
	err := c.cc.Invoke(ctx, "/standard.Swaper/UpdateUnitDataDestroyTimeByKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swaperClient) UpdateUnitDataEffectiveTimeByKey(ctx context.Context, in *UpdateUnitDataEffectiveTimeByKeyRequest, opts ...grpc.CallOption) (*UpdateUnitDataEffectiveTimeByKeyResponse, error) {
	out := new(UpdateUnitDataEffectiveTimeByKeyResponse)
	err := c.cc.Invoke(ctx, "/standard.Swaper/UpdateUnitDataEffectiveTimeByKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SwaperServer is the server API for Swaper service.
type SwaperServer interface {
	CreateUnitData(context.Context, *CreateUnitDataRequest) (*CreateUnitDataResponse, error)
	GetUnitDataByKey(context.Context, *GetUnitDataByKeyRequest) (*GetUnitDataByKeyResponse, error)
	DestroyUnitDataByKey(context.Context, *DestroyUnitDataByKeyRequest) (*DestroyUnitDataByKeyResponse, error)
	UpdateUnitDataBodyByKey(context.Context, *UpdateUnitDataBodyByKeyRequest) (*UpdateUnitDataBodyByKeyResponse, error)
	UpdateUnitDataExpiryTimeByKey(context.Context, *UpdateUnitDataExpiryTimeByKeyRequest) (*UpdateUnitDataExpiryTimeByKeyResponse, error)
	UpdateUnitDataDestroyTimeByKey(context.Context, *UpdateUnitDataDestroyTimeByKeyRequest) (*UpdateUnitDataDestroyTimeByKeyResponse, error)
	UpdateUnitDataEffectiveTimeByKey(context.Context, *UpdateUnitDataEffectiveTimeByKeyRequest) (*UpdateUnitDataEffectiveTimeByKeyResponse, error)
}

// UnimplementedSwaperServer can be embedded to have forward compatible implementations.
type UnimplementedSwaperServer struct {
}

func (*UnimplementedSwaperServer) CreateUnitData(ctx context.Context, req *CreateUnitDataRequest) (*CreateUnitDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUnitData not implemented")
}
func (*UnimplementedSwaperServer) GetUnitDataByKey(ctx context.Context, req *GetUnitDataByKeyRequest) (*GetUnitDataByKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUnitDataByKey not implemented")
}
func (*UnimplementedSwaperServer) DestroyUnitDataByKey(ctx context.Context, req *DestroyUnitDataByKeyRequest) (*DestroyUnitDataByKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DestroyUnitDataByKey not implemented")
}
func (*UnimplementedSwaperServer) UpdateUnitDataBodyByKey(ctx context.Context, req *UpdateUnitDataBodyByKeyRequest) (*UpdateUnitDataBodyByKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUnitDataBodyByKey not implemented")
}
func (*UnimplementedSwaperServer) UpdateUnitDataExpiryTimeByKey(ctx context.Context, req *UpdateUnitDataExpiryTimeByKeyRequest) (*UpdateUnitDataExpiryTimeByKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUnitDataExpiryTimeByKey not implemented")
}
func (*UnimplementedSwaperServer) UpdateUnitDataDestroyTimeByKey(ctx context.Context, req *UpdateUnitDataDestroyTimeByKeyRequest) (*UpdateUnitDataDestroyTimeByKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUnitDataDestroyTimeByKey not implemented")
}
func (*UnimplementedSwaperServer) UpdateUnitDataEffectiveTimeByKey(ctx context.Context, req *UpdateUnitDataEffectiveTimeByKeyRequest) (*UpdateUnitDataEffectiveTimeByKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUnitDataEffectiveTimeByKey not implemented")
}

func RegisterSwaperServer(s *grpc.Server, srv SwaperServer) {
	s.RegisterService(&_Swaper_serviceDesc, srv)
}

func _Swaper_CreateUnitData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUnitDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwaperServer).CreateUnitData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/standard.Swaper/CreateUnitData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwaperServer).CreateUnitData(ctx, req.(*CreateUnitDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Swaper_GetUnitDataByKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUnitDataByKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwaperServer).GetUnitDataByKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/standard.Swaper/GetUnitDataByKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwaperServer).GetUnitDataByKey(ctx, req.(*GetUnitDataByKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Swaper_DestroyUnitDataByKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroyUnitDataByKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwaperServer).DestroyUnitDataByKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/standard.Swaper/DestroyUnitDataByKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwaperServer).DestroyUnitDataByKey(ctx, req.(*DestroyUnitDataByKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Swaper_UpdateUnitDataBodyByKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUnitDataBodyByKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwaperServer).UpdateUnitDataBodyByKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/standard.Swaper/UpdateUnitDataBodyByKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwaperServer).UpdateUnitDataBodyByKey(ctx, req.(*UpdateUnitDataBodyByKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Swaper_UpdateUnitDataExpiryTimeByKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUnitDataExpiryTimeByKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwaperServer).UpdateUnitDataExpiryTimeByKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/standard.Swaper/UpdateUnitDataExpiryTimeByKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwaperServer).UpdateUnitDataExpiryTimeByKey(ctx, req.(*UpdateUnitDataExpiryTimeByKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Swaper_UpdateUnitDataDestroyTimeByKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUnitDataDestroyTimeByKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwaperServer).UpdateUnitDataDestroyTimeByKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/standard.Swaper/UpdateUnitDataDestroyTimeByKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwaperServer).UpdateUnitDataDestroyTimeByKey(ctx, req.(*UpdateUnitDataDestroyTimeByKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Swaper_UpdateUnitDataEffectiveTimeByKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUnitDataEffectiveTimeByKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwaperServer).UpdateUnitDataEffectiveTimeByKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/standard.Swaper/UpdateUnitDataEffectiveTimeByKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwaperServer).UpdateUnitDataEffectiveTimeByKey(ctx, req.(*UpdateUnitDataEffectiveTimeByKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Swaper_serviceDesc = grpc.ServiceDesc{
	ServiceName: "standard.Swaper",
	HandlerType: (*SwaperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUnitData",
			Handler:    _Swaper_CreateUnitData_Handler,
		},
		{
			MethodName: "GetUnitDataByKey",
			Handler:    _Swaper_GetUnitDataByKey_Handler,
		},
		{
			MethodName: "DestroyUnitDataByKey",
			Handler:    _Swaper_DestroyUnitDataByKey_Handler,
		},
		{
			MethodName: "UpdateUnitDataBodyByKey",
			Handler:    _Swaper_UpdateUnitDataBodyByKey_Handler,
		},
		{
			MethodName: "UpdateUnitDataExpiryTimeByKey",
			Handler:    _Swaper_UpdateUnitDataExpiryTimeByKey_Handler,
		},
		{
			MethodName: "UpdateUnitDataDestroyTimeByKey",
			Handler:    _Swaper_UpdateUnitDataDestroyTimeByKey_Handler,
		},
		{
			MethodName: "UpdateUnitDataEffectiveTimeByKey",
			Handler:    _Swaper_UpdateUnitDataEffectiveTimeByKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "standard.proto",
}
